### ISSUE TITLE
Aladin-lite does not appear in new viewers list

### ISSUE THREAD

**Issue by ManonMarchand** [glue-viz/glue-aladin#1]
I just installed the plugin and it appears as checked into the pluging manager of my glue instance. But when I try to create a  new view via 

```
Data Manager > Create new viewer
```
aladin does not appear in the scrolling menu. 

Do you know what is happening here?

I'm using the conda install in python 3.9 on a ubuntu 20.

**Comment by astrofrog** [comment]
I'll look into this!

**Comment by astrofrog** [comment]
@ManonMarchand - I think this should be fixed by https://github.com/glue-viz/glue-aladin/pull/3 although the viewer isn't fully working yet (but it will appear in the list and open up correctly).
